### ISSUE TITLE
Dataset description

### ISSUE THREAD

**Issue by Jhin3433** [CogComp/APSI#1]
Hi~ Could you explain to me the detailed fields description exiting in the dataset?  I have difficulty in recognizing the meaning of each field. Thanks!
![image](https://user-images.githubusercontent.com/33836571/130195003-32e9b43d-e811-442a-bcb7-f21fcb1ae742.png)

**Comment by panda0881** [comment]
Hi,

Thanks for your question. "title", "section", and "subevents" are the original text. Fields ended with activities are the activities extracted by the ASER extraction pipeline. Fileds ended with "srls" are SRL parsing results. "v_o" means verb and object.
